### PR TITLE
Migrate to bullmq

### PR DESCRIPTION
**Pull request by codetheweb**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

Moves to bullmq. Partially resolves https://github.com/nestjs/bull/issues/202.

## Does this PR introduce a breaking change?
```
[x] Yes
[ ] No
```

THe function signatures for job processors have changed slightly. There is no longer a DoneCallback and processors must return a Promise.

## Other information

These docs need to be updated: https://docs.nestjs.com/techniques/queues

### CODE REVIEW

**Comment by sorensenNiels** [comment]
What can we do to get this pr into master and finalize a release

**Comment by kevinvdburgt** [comment]
> What can we do to get this pr into master and finalize a release

It seems that the docs should be updated first.

@kamilmysliwiec any plans to release this upgrade from bull to bullmq? Or should this become another package as it contains breaking changes?

**Comment by sorensenNiels** [comment]
Releasing a bullmq package and later on deprecating the bull package would be great for most. IMHOP.

**Review by tranphuoctien — APPROVED** [review]

**Comment by tientp-floware** [comment]
Please merge soon, It's very helpful.

**Comment by kamilmysliwiec** [comment]
As I've mentioned in the past issues, we don't plan to migrate this package to bullmq. Instead, we'll very likely publish a separate module for this (to avoid breaking changes). Locking this PR for the time being to avoid spam (and saving it for future reference).

**Comment by kamilmysliwiec** [comment]
https://github.com/nestjs/bull/pull/1129

**Pull request closed without merging**
