### PR TITLE
feat: added ability to register workers manually

### PR DESCRIPTION
**Pull request by idbenami**
## PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/nestjs/nest/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type
What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
When `BullExplorer`.`OnModuleInit` is finished the processors are starting to process jobs from the queue while my app isn't ready, and there's no way to tell the processors when they can start taking jobs.

Issue Number: [2030](https://github.com/nestjs/bull/issues/2030)

## What is the new behavior?
Added an option to manually register workers and event listeners using a provider called `BullRegistrator`. by default nothing has changed, but if `manualRegistration` is set to `true` the developer need to call `BullRegistrator`.`register` in order for the workers and event listeners to start working.

## Does this PR introduce a breaking change?
- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by idbenami** [comment]
@kamilmysliwiec any estimation on merging?

**Comment by ramigoldvarg** [comment]
Is there an estimate when this will be added? Waiting for this capability

**Comment by jarPotato** [comment]
Waiting for this to be merged. It should also help #2017 .

**Comment by idbenami** [comment]
@kamilmysliwiec is there any blocker?

**Comment by kamilmysliwiec** [comment]
LGTM

**Pull request merged**
